# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Build & Publish Containers

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
  release:
    types:
      - created

env:
  REGISTRY_USER: ${{ github.repository_owner }}
  REPO_NAME: 'barsava_talar'

jobs:
  build-and-publish:
    name: Build & Publish
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        include:
          - path: app

    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: â¤µï¸ Checkout Repository
        uses: actions/checkout@v4

      - name: ğŸ— Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: ğŸ— Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: ğŸ— Cache Docker Layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: buildx-${{ runner.os }}-${{ matrix.path }}-${{ github.sha }}
          restore-keys: |
            buildx-${{ runner.os }}-${{ matrix.path }}-

      - name: ğŸ” Log into ghcr.io Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: <your-github-username>
          password: ${{ secrets.GHCR_PAT }}

      - name: Extract Container Metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ env.REGISTRY_USER }}/${{ env.REPO_NAME }}

          tags: |
            type=ref,event=branch,enable=${{ github.event_name != 'pull_request' }}
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}
            type=sha,format=short,enable=${{ github.event_name != 'pull_request' }}
            type=raw,value=pr-${{ github.event.pull_request.number }},enable=${{ github.event_name == 'pull_request' }}
            type=sha,format=short,prefix=pr-,enable=${{ github.event_name == 'pull_request' }}

          labels: |
            org.opencontainers.image.title=${{ env.REPO_NAME }}
            org.opencontainers.image.source=${{ github.repositoryUrl }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.created=${{ github.event.head_commit.timestamp }}

          flavor: |
            latest=false

      - name: ğŸš€ Build and Push Container Image
        id: build-and-push
        uses: docker/build-push-action@v6
        with:
          file: ./Dockerfile
          push: ${{ github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            BUILD_DATE=${{ github.event.repository.updated_at }}
            BUILD_REV=${{ github.sha }}

      - name: ğŸ–‹ Install Cosign
        uses: sigstore/cosign-installer@v3

      - name: ğŸ–‹ Sign Container Images
        run: |
          for image in ${{ steps.meta.outputs.images }}; do
            echo "Signing ${image}@${{ steps.build-and-push.outputs.digest }}"
            cosign sign --yes "${image}@${{ steps.build-and-push.outputs.digest }}"
          done
